name: CI Flask App WF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Code with Black
        run: |
          black .

      - name: Prepare Reports Directory
        run: mkdir -p tests/reports/

      - name: Run Tests with Coverage
        run: |
          pytest --cov=app --junitxml=tests/reports/results.xml tests/

      # - name: Upload Coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tests/reports/
          retention-days: 3

      - name: Report Test Results
        if: failure()
        run: |
          echo "Some tests have failed. Check the 'test-results' artifact for more details."
